
SELECT * 
FROM FUNCIONARIO
WHERE Salario > 30000

SELECT *
FROM FUNCIONARIO
WHERE YEAR(Datanasc) >= 1972


SELECT F.Sexo, COUNT(F.Sexo) AS 'Quantidade'
FROM FUNCIONARIO F
GROUP BY F.Sexo
HAVING COUNT(F.Sexo) <= 5