

--SELECT DISTINCT F.Pnome,F.Salario
--FROM FUNCIONARIO AS F

--SELECT *
--FROM FUNCIONARIO
--WHERE Pnome = 'João'


--SELECT *
--FROM FUNCIONARIO AS F
--WHERE F.Sexo = 'M' AND F.Salario >= 30000 

SELECT * 
FROM FUNCIONARIO
WHERE Endereco LIKE '%São Paulo%'
OR Endereco LIKE '%Curitiba%';

SELECT * 
FROM FUNCIONARIO F
WHERE NOT F.Endereco LIKE '%São Paulo%'

SELECT * 
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC

SELECT * 
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor NULL;

SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL;

SELECT MIN(Salario)
FROM FUNCIONARIO

SELECT MAX(Salario)
FROM FUNCIONARIO

SELECT COUNT(Cpf)
FROM FUNCIONARIO

SELECT * FROM FUNCIONARIO

