

--SELECT DISTINCT F.Pnome,F.Salario
--FROM FUNCIONARIO AS F

--SELECT *
--FROM FUNCIONARIO
--WHERE Pnome = 'João'


--SELECT *
--FROM FUNCIONARIO AS F
--WHERE F.Sexo = 'M' AND F.Salario >= 30000 

SELECT * 
FROM FUNCIONARIO
WHERE Endereco LIKE '%São Paulo%'
OR Endereco LIKE '%Curitiba%';

SELECT * 
FROM FUNCIONARIO F
WHERE NOT F.Endereco LIKE '%São Paulo%'

SELECT * 
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC

SELECT * 
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor NULL;

SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL;

SELECT MIN(Salario)
FROM FUNCIONARIO

SELECT MAX(Salario)
FROM FUNCIONARIO

SELECT COUNT(Cpf)
FROM FUNCIONARIO

DECLARE @salarioAvg DECIMAL(10, 2)
SET @salarioAvg = (SELECT AVG(Salario) 
	FROM FUNCIONARIO)

PRINT @salarioAvg

DECLARE @salarioSum DECIMAL(10, 2)
SET @salarioSum = (SELECT SUM(Salario)
	FROM FUNCIONARIO)

PRINT 'Salario total: ' + CAST(@salarioSum AS VARCHAR(10));

SELECT *
FROM FUNCIONARIO
WHERE Salario IN (25000, 30000)
ORDER BY Salario ASC

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Dnr = 5
AND Salario BETWEEN 30000 AND 40000

SELECT F.Pnome, F.Unome, F.Endereco, D.Dnome
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON F.Dnr = D.Dnumero
WHERE D.Dnumero = 5

SELECT *
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
JOIN PROJETO P
ON D.Dnumero = P.Dnum
WHERE P.Projnome = 'ProdutoX'

SELECT DISTINCT F.*
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
JOIN PROJETO P
ON D.Dnumero = P.Dnum
WHERE P.Projlocal LIKE 'Mauá'

SELECT 
f.sexo, COUNT(F.Sexo) AS 'Número de funcionarios'
FROM FUNCIONARIO F
GROUP BY F.Sexo

SELECT D.Dnome,COUNT(F.Cpf)
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome

SELECT D.Dnome, AVG(F.Salario)
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome

SELECT P.Projnome, AVG(TE.Horas)
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
JOIN PROJETO P
ON P.Dnum = D.Dnumero
JOIN TRABALHA_EM TE
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome

SELECT D.Dnome,MAX(F.Salario)
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome

SELECT 
D.Dnome, COUNT(F.Cpf) AS NumFuncionarios
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome
HAVING 
COUNT(F.Cpf) > 3;

SELECT F.*
FROM FUNCIONARIO F
WHERE EXISTS (SELECT 1
	FROM DEPARTAMENTO D
	WHERE D.Cpf_gerente = F.Cpf)

SELECT D.Dnome, D.Dnumero
FROM DEPARTAMENTO D
WHERE EXISTS (
	SELECT 1
	FROM PROJETO P
	WHERE P.Dnum = D.Dnumero
	);

SELECT Pnome, Unome, Salario
FROM FUNCIONARIO
WHERE SALARIO > ANY (
	SELECT Salario
	FROM FUNCIONARIO
	JOIN DEPARTAMENTO ON Dnr = Dnumero
	WHERE Dnome = 'Administração'
	)

DECLARE @IdadeJen INT;

SELECT @IdadeJen = DATEDIFF(YEAR, Datanasc, GETDATE())
FROM FUNCIONARIO
WHERE Pnome = 'Jennifer'
PRINT 'Idade da Jennifer: ' + CAST(@IdadeJen AS VARCHAR)

DECLARE @NomeDep VARCHAR(15);

SELECT @NomeDep = (
	SELECT Dnome
	FROM DEPARTAMENTO
	WHERE Dnumero = 2
)

PRINT 'Nome do departamento' + @NomeDep


DECLARE @MediaSalarial DECIMAL(10, 2), @NomeFuncionario VARCHAR(20), @Salario DECIMAL(10, 2);

SET @NomeFuncionario = 'Jorge';

SELECT @MediaSalarial = AVG(Salario) FROM FUNCIONARIO

SELECT @Salario = Salario FROM FUNCIONARIO WHERE Pnome = @NomeFuncionario

IF @Salario < @MediaSalarial
	PRINT 'RECEBE ABAIXO DA MEDIA SALARIAL'
ELSE
	PRINT 'RECEBE ACIMA DA MEDIA SALARIAL'


SELECT * FROM FUNCIONARIO
