--TRANSAÇÃO 1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION

SELECT * FROM FUNCIONARIO;

--PAUSA POR 10 SEGUNDOS
WAITFOR DELAY '00:00:10';
COMMIT TRANSACTION;

--TRANSAÇÃO 2
BEGIN TRANSACTION 

INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, cpf, Datanasc, Endereco, 
Sexo, Salario, Cpf_supervisor, Dnr)
VALUES ('Carlitos', 'R', 'Almeida', '11944515582', '1991-07-02', 'av. Brasil, 500', 'M',
4500, NULL, 1);

COMMIT TRANSACTION;